version: "3.9"
services:

  news_cryptobot:
    restart: always
    container_name: coinbase_parser
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./logs:/news/logs
      - ./database/files:/news/database/files